### ISSUE TITLE
Could not import the name: cartridge_stripe.forms.OrderForm: cannot import name SortedDict

### ISSUE THREAD

**Issue by megatran** [readevalprint/cartridge-stripe#11]
It seems this plugin no longer works with django 1.9

could you please fix it?

"Could not import the name: cartridge_stripe.forms.OrderForm: cannot import name SortedDict"

I think you a possible fix is to change sortedDict to "collections.OrderedDict"
